version: "3.9"

services:
  app:
    # build dockerfile in current directory
    build:
      context: .
    # map port 8000 in local machine to port 8000 in docker container
    ports:
      - "8000:8000"
    # map directories into container
    volumes:
      - ./app:/app
    # command used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"