---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # run test on specified machine
    runs-on: ubuntu-20.04
    steps:
      # human-readable name/action
      - name: Login to Docker Hub
        # premade action provided in Github action repository
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"